name: "Caller"

on:
  workflow_dispatch:
    inputs:
      workflow:
        type: text
        required: true

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "WORKFLOW=callable1" >> $GITHUB_OUTPUT

  call:
    needs: set-env
    uses: ./.github/workflows/${{ inputs.workflow }}.yml
