name: "Caller"

on:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/callable.yaml
    with:
      gate: "true"
  run2:
    uses: ./.github/workflows/callable.yaml
    with:
      gate: "false"
  run3:
    uses: ./.github/workflows/callable.yaml
  run4:
    uses: ./.github/workflows/callable.yaml
    with:
      gate: true
  run5:
    uses: ./.github/workflows/callable.yaml
    with:
      gate: false
