name: "Caller"

on:
  workflow_dispatch:
    inputs:
      service:
        type: text
        required: true

jobs:
  call-${{ inputs.service }}:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.service }}
