name: "Caller"

on:
  workflow_dispatch:

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: echo "MY_VAL=1" >> $GITHUB_OUTPUT
      
      - run: |
          echo "${{ steps.test.outputs.MY_VAL }}"
          if [[ ${{ steps.test.outputs.MY_VAL }} > 2 ]]; then
            echo "yes"
          else
            echo "no"
          fi
