name: "Caller"

on:
  workflow_dispatch:
    inputs:
      service:
        type: text
        required: true

jobs:
  run:
    name: run ${{ inputs.service }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.service }}
