name: Reusable workflow example

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  test:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"
