name: "Caller"

on:
  workflow_dispatch:
    inputs:
      workflow:
        type: choice
        options:
          - callable1
          - callable2

jobs:
  call:
    uses: ./.github/workflows/${{ inputs.workflow }}.yaml
