name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Parse jobs to ignore
        run: |
          echo "$GITHUB_REF"
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored: |
            test1,
            test2,
            test3
          ref: refs/head/master
