name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Parse jobs to ignore
        run: |
          echo "$GITHUB_REF"
      - name: Run Merge Gatekeeper
        uses: dispatchhealth/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored: test1,test2,test3,main-job (myfile1.txt)
          ref: refs/heads/master
          timeout: 30
