name: "Test"

on:
  push:
    branches:
      - "master"

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "hi"
        if: ${{ failure() && github.ref_name == 'master' }}
      
      
